workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Setup iOS Platform and Build
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          if [ -d "dist" ]; then cp -r dist/* www/; fi
          npx cap sync ios
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -destination "generic/platform=iOS" build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/Debug-iphoneos/*.app
      - build/ios/ipa/*.ipa